# Generated by Django 4.2.2 on 2024-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=64)),
                ('placeholder2', models.CharField(max_length=64)),
                ('placeholder3', models.IntegerField()),
            ],
        ),
    ]
