# Generated by Django 4.2.2 on 2024-02-21 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdxtelework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeleworkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('bench_assigned', models.CharField(choices=[('bench1', 'Bench 1'), ('bench2', 'Bench 2'), ('bench3', 'Bench 3'), ('other', 'Other')], max_length=100)),
                ('other_bench_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('completion_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdxtelework.completionreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task', models.CharField(max_length=200)),
                ('completion_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='mdxtelework.completionreport')),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='completionreport',
            name='telework_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mdxtelework.teleworkrequest'),
        ),
    ]
